### ISSUE TITLE
2020-07-05：如何写一个CSS样式对象化工具？

### ISSUE THREAD

**Issue by ppambler** [ppambler/plan-todo#30]
``` css
.xxx {
  color: #ec4863;
  text-decoration: none;
}
```

to

``` js
{
  color: '#ec4863',
  textDecoration: 'none'
}
```
